[build]
  publish = "/"
  command = "echo 'Static Digital Garden ready for deployment'"

[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for Digital Garden
[[redirects]]
  from = "/index.html"
  to = "/README"
  status = 301

[[redirects]]
  from = "/"
  to = "/README"
  status = 200

# Handle markdown files
[[redirects]]
  from = "/*.md"
  to = "/:splat"
  status = 200

# 404 redirect to home
[[redirects]]
  from = "/*"
  to = "/README"
  status = 404 